apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-namecom
spec:
  acme:
    email: taiwo@badex.tv          # ✅ Replace this
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-namecom
    solvers:
    - dns01:
        webhook:
          groupName: acme.name.com
          solverName: namedotcom
          config:
            username: BadexTV              # ✅ Use your actual domain name host username
            apitokensecret:
              name: namedotcom-credentials
              key: api-token