apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kiali.org/helm-charts
    targetRevision: v1.73.0
    chart: kiali-server
    helm:
      parameters:
        - name: auth.strategy
          value: anonymous

        - name: deployment.accessible_namespaces
          value: '**'
        - name: deployment.namespace
          value: istio-system

        - name: ingress.enabled
          value: 'true'
        - name: ingress.class_name
          value: nginx
        - name: ingress.annotations.cert-manager\.io/cluster-issuer
          value: letsencrypt-namecom
        - name: ingress.annotations.nginx\.ingress\.kubernetes\.io/ssl-redirect
          value: 'true'
        - name: ingress.annotations.nginx\.ingress\.kubernetes\.io/force-ssl-redirect
          value: 'true'
        - name: ingress.hosts[0].name
          value: kiali.badex.dev
        - name: ingress.hosts[0].path
          value: /
        - name: ingress.hosts[0].tls
          value: 'true'
        - name: ingress.hosts[0].tlsSecret
          value: kiali-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true