apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/turbo-badex/kubernetes-homelab
    targetRevision: main
    path: argocd-apps/longhorn
    directory:
      recurse: true
      include: ingress.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true