apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: v1.9.0
    helm:
      values: |
        defaultSettings:
          defaultReplicaCount: 2
          defaultDataPath: /var/lib/longhorn
          backupTarget: ""

        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
            cert-manager.io/cluster-issuer: "letsencrypt-namecom"
          host: longhorn.badex.dev
          tls: true
          tlsSecret: longhorn-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy: {}