apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/turbo-badex/kubernetes-homelab
    targetRevision: main
    path: argocd-apps/minio
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy: {}