apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://releases.rancher.com/server-charts/latest
    chart: rancher
    targetRevision: 2.11.1
    helm:
      values: |
        hostname: rancher.badex.dev
        replicas: 1
        ingress:
          tls:
            source: secret
            secretName: tls-rancher
  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-system
  syncPolicy: {}