nameOverride: "minio"
fullnameOverride: "minio"

mode: standalone

image:
  repository: quay.io/minio/minio
  tag: RELEASE.2023-10-25T06-33-25Z

mcImage:
  repository: quay.io/minio/mc
  tag: RELEASE.2024-11-21T17-21-54Z

rootUser: ""
rootPassword: ""
existingSecret: minio-login

persistence:
  enabled: true
  storageClass: nfs
  accessMode: ReadWriteMany
  size: 150Gi

service:
  type: ClusterIP
  port: "9000"

consoleService:
  type: ClusterIP
  port: "9001"

securityContext:
  enabled: true
  runAsUser: 65534
  runAsGroup: 100
  fsGroup: 100
  fsGroupChangePolicy: "OnRootMismatch"

metrics:
  serviceMonitor:
    enabled: true
    includeNode: true
    public: true
    namespace: minio
    interval: 60s
    scrapeTimeout: 30s

resources:
  requests:
    memory: 2Gi
    cpu: 500m
  limits:
    memory: 4Gi
    cpu: 1