apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-nfs-pvc
  namespace: minio
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: minio-nfs-pv        # Explicitly bind to the PV above
  storageClassName: ""            # Must be empty to match PV