apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-nfs-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""  # Explicitly empty since this is statically bound
  nfs:
    server: 10.0.0.119            # Your Synology NAS static IP
    path: /volume1/minio          # Your shared folder on NAS