apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec:
  secretName: argocd-tls
  issuerRef:
    name: letsencrypt-namecom
    kind: ClusterIssuer
  commonName: argocd.badex.dev
  dnsNames:
    - argocd.badex.dev
  privateKey:
    rotationPolicy: Always