apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rancher-cert
  namespace: cattle-system
spec:
  secretName: tls-rancher-ingress
  issuerRef:
    name: letsencrypt-namecom
    kind: ClusterIssuer
  commonName: rancher.badex.dev
  dnsNames:
    - rancher.badex.dev
  privateKey:
    rotationPolicy: Always
  usages:
    - digital signature
    - key encipherment