# argocd-apps/rancher/certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rancher-cert
  namespace: cattle-system
spec:
  secretName: rancher-tls
  issuerRef:
    name: letsencrypt-namecom
    kind: ClusterIssuer
  commonName: rancher.badex.dev
  dnsNames:
    - rancher.badex.dev